<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Cotisation extends \Entities\Cotisation implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setDebut($debut)
    {
        $this->__load();
        return parent::setDebut($debut);
    }

    public function getDebut()
    {
        $this->__load();
        return parent::getDebut();
    }

    public function setFin($fin)
    {
        $this->__load();
        return parent::setFin($fin);
    }

    public function getFin()
    {
        $this->__load();
        return parent::getFin();
    }

    public function setMontant($montant)
    {
        $this->__load();
        return parent::setMontant($montant);
    }

    public function getMontant()
    {
        $this->__load();
        return parent::getMontant();
    }

    public function setCreatedAt($createdAt)
    {
        $this->__load();
        return parent::setCreatedAt($createdAt);
    }

    public function getCreatedAt()
    {
        $this->__load();
        return parent::getCreatedAt();
    }

    public function setUpdatedAt($updatedAt)
    {
        $this->__load();
        return parent::setUpdatedAt($updatedAt);
    }

    public function getUpdatedAt()
    {
        $this->__load();
        return parent::getUpdatedAt();
    }

    public function setPersonne(\Entities\Personne $personne = NULL)
    {
        $this->__load();
        return parent::setPersonne($personne);
    }

    public function getPersonne()
    {
        $this->__load();
        return parent::getPersonne();
    }


    public function __sleep()
    {
<<<<<<< HEAD
        return array('__isInitialized__', 'id', 'debut', 'fin', 'montant', 'created_at', 'updated_at', 'personne');
=======
        return array('__isInitialized__', 'id', 'debut', 'fin', 'montant', 'personne');
>>>>>>> aaca4e16dd970ea00090939d0522c4336b31535a
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}